import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createServerClient } from "@/utils/supabase/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export async function generateMetadata(): Promise<Metadata> {
  try {
    const supabase = await createServerClient()
    const { data } = await supabase.from('site_settings').select('settings').eq('id', 1).single()
    const s = data?.settings ?? {}
    return {
      title: s.site_title || '클래시스 폼 생성 템플릿',
      description: s.site_description || 'Generated by MKT',
      icons: s.favicon_url ? { icon: s.favicon_url } : undefined,
      openGraph: s.og_image_url ? { images: [s.og_image_url] } : undefined,
    }
  } catch {
    return {
      title: '클래시스 폼 생성 템플릿',
      description: 'Generated by MKT',
    }
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>{children}</body>
    </html>
  );
}
